SET NAMES 'UTF8MB4';
DROP DATABASE IF EXISTS tareas;
CREATE DATABASE IF NOT EXISTS tareas DEFAULT CHARACTER SET UTF8MB4;
USE tareas;

CREATE TABLE tareas (
    id_tarea INTEGER PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(200) NOT NULL,
    descripcion VARCHAR(300),
    estado BOOLEAN NOT NULL DEFAULT 0,
    creadoAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);